#!/bin/sh
#
# Copyright (c) 2005 CodeSourcery
# Copyright (c) 2013 Stefan Seefeld
# All rights reserved.
#
# This file is part of OpenVSIP. It is made available under the
# license contained in the accompanying LICENSE.BSD file.

aclocal -I m4
# Generate 'src/ovxx/detail/config.hpp.in' by inspecting 'configure.ac'
autoheader
# Generate 'configure' from 'configure.ac'
autoconf

# Tell configure to ignore non-executable/object files generated by
# greenhills compiler
cat configure | sed -e "s,\*.xcoff,\*.xcoff | *.dla | *.dnm | *.dbo | *.map," > configure.tmp
mv configure.tmp configure
chmod +x configure

