######################################################### -*-Makefile-*-
#
# Contents: Makefile for VSIPL++ example programs.
#
########################################################################

targets := dense stride layout

include ../common.mk
