######################################################### -*-Makefile-*-
#
# Contents: Makefile for VSIPL++ example programs.
#
########################################################################

targets := example1 vmul

include common.mk
