#! /bin/sh

# Check result of single-precision run

DIR="."

NRANGE=256
NPULSE=64
NTAPS=8
NFRAME=4
THRESH=-190


$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   test-8/hh-d-$NTAPS-$NFRAME.bin		\
	-ref test-8/ref-plain/hh-d-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   test-8/hv-d-$NTAPS-$NFRAME.bin		\
	-ref test-8/ref-plain/hv-d-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   test-8/vh-d-$NTAPS-$NFRAME.bin		\
	-ref test-8/ref-plain/vh-d-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   test-8/vv-d-$NTAPS-$NFRAME.bin		\
	-ref test-8/ref-plain/vv-d-$NTAPS-$NFRAME.bin	\
	-chk $THRESH
