#! /bin/sh

# file to run double precision C simulator for four frames, all polarizations
#   and with 8-tap filter.

DIR="."
TDIR="test-48"
PREC="d"

NRANGE=2048
NPULSE=512

$DIR/mit-sarsim				\
    -double				\
    -nrange $NRANGE			\
    -npulse $NPULSE			\
    -nframe 4				\
    -niq 48				\
    -itype 0				\
    -hhon 1				\
    -hvon 1				\
    -vhon 1				\
    -vvon 1				\
    -i   $TDIR/data/radar-tb-48.bin	\
    -iqe $TDIR/data/iqe-48.bin	\
    -iqo $TDIR/data/iqo-48.bin	\
    -krn $TDIR/data/krn-48.bin	\
    -eq  $TDIR/data/equ-48.bin	\
    -rcs $TDIR/data/rcs-48.bin	\
    -ohh $TDIR/hh-$PREC-48-4.bin		\
    -ohv $TDIR/hv-$PREC-48-4.bin		\
    -ovh $TDIR/vh-$PREC-48-4.bin		\
    -ovv $TDIR/vv-$PREC-48-4.bin
