#! /bin/sh

# Check result of single-precision run

TDIR=test-8

NRANGE=256
NPULSE=64
NTAPS=8
NFRAME=4
PREC=s

# DAT2XV=/home/jules/csl/src/apps/SarSim/work/source/c/dat2xv
DAT2XV=./dat2xv

$DAT2XV -nrange $NRANGE -npulse $NPULSE -nframe $NFRAME	\
	-i   $TDIR/hh-$PREC-$NTAPS-$NFRAME.bin		\
	-o   $TDIR/hh-temp.xv

rawtopgm -headerskip 28 $NPULSE $NPULSE $TDIR/hh-temp.xv	\
	> $TDIR/hh-$PREC-$NTAPS-$NFRAME.pgm

rm $TDIR/hh-temp.xv
