######################################################### -*-Makefile-*-
#
# Contents: Makefile for VSIPL++ example programs.
#
########################################################################

targets := vadd

include ../common.mk
