######################################################### -*-Makefile-*-
#
# Contents: Makefile for VSIPL++ example programs.
#
########################################################################

targets := basic eval diagnostics memory

include ../common.mk
