/* This linker script is used for plugins.  The SPU resident will load
 * the plugin at a specific location in SPU memory.  For the plugin
 * code to work correctly, it must be linked with that specific
 * location in mind.
 *
 * This script links the plugin to be loaded at SPU memory address 0x4000
 */

SECTIONS
{
  . = 0x4000;
  .text : { *(.text) }
  .data : { *(.data) }
  .bss : { *(.bss) }
}
