######################################################### -*-Makefile-*-
#
# Contents: Makefile for VSIPL++ example signal programs.
#
########################################################################

targets := fft fft2d

include ../common.mk
