#! /bin/sh

# Check result of single-precision run

DIR="."

NRANGE=2048
NPULSE=512
NTAPS=48
NFRAME=4
ATTR=attr
THRESH=-190
TDIR=test-48
PREC=s


$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/hh-$PREC-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-$ATTR/hh-$PREC-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/hv-$PREC-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-$ATTR/hv-$PREC-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/vh-$PREC-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-$ATTR/vh-$PREC-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/vv-$PREC-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-$ATTR/vv-$PREC-$NTAPS-$NFRAME.bin	\
	-chk $THRESH
