#! /bin/sh

# Check result of single-precision run

DIR="."

TDIR=test-8
NRANGE=256
NPULSE=64
NTAPS=8
NFRAME=4
THRESH=-190


$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/hh-s-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-plain/hh-s-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/hv-s-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-plain/hv-s-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/vh-s-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-plain/vh-s-$NTAPS-$NFRAME.bin	\
	-chk $THRESH

$DIR/histcmp -nrange $NRANGE -npulse $NPULSE			\
	-i   $TDIR/vv-s-$NTAPS-$NFRAME.bin		\
	-ref $TDIR/ref-plain/vv-s-$NTAPS-$NFRAME.bin	\
	-chk $THRESH
